name=BT1026_Driver
version=2.0.0
author=ValeraBat
maintainer=ValeraBat
sentence=A universal, non-RTOS superloop C++ driver for QCC3034/QCC5125 Bluetooth modules.
paragraph=Compatible with almost all MCUs. Allows abstract stream injection and replaces FreeRTOS dependencies.
category=Device Control
url=https://github.com/ValeraBat/BT1026D_Driver
architectures=*
includes=UniversalBT1026.h
